"""SFT training for text-only BCI spelling correction.

Fine-tunes Qwen3-4B-Instruct with LoRA on the correction dataset
generated by generate_correction_data.py.

No EEG embeddings — pure text-to-text correction.

Usage:
    uv run python scripts/train_correction.py \
        --data_dir data/correction \
        --output_dir output/correction \
        --model_name Qwen/Qwen3-4B-Instruct-2507
"""

import argparse
import json
from pathlib import Path

import torch
from peft import LoraConfig, get_peft_model
from torch.utils.data import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    EarlyStoppingCallback,
    Trainer,
    TrainingArguments,
)


class CorrectionDataset(Dataset):
    """Loads correction JSONL and tokenizes as chat messages."""

    def __init__(self, jsonl_path, tokenizer, max_length=512):
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.samples = []

        with open(jsonl_path) as f:
            for line in f:
                self.samples.append(json.loads(line))

        print(f"Loaded {len(self.samples)} samples from {jsonl_path}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        sample = self.samples[idx]
        messages = sample["messages"]

        # Use Qwen's chat template to format
        text = self.tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=False,
        )

        # Tokenize
        encoded = self.tokenizer(
            text, truncation=True, max_length=self.max_length,
            return_tensors="pt", padding=False,
        )
        input_ids = encoded["input_ids"].squeeze(0)
        attention_mask = encoded["attention_mask"].squeeze(0)

        # Build labels: mask everything before assistant response
        labels = input_ids.clone()

        # Find the assistant turn start — mask all tokens before it
        # Qwen3 format: ...<|im_start|>assistant\n{response}<|im_end|>
        assistant_marker = self.tokenizer.encode(
            "<|im_start|>assistant\n", add_special_tokens=False,
        )
        marker_len = len(assistant_marker)

        # Find marker position
        marker_pos = -1
        for i in range(len(input_ids) - marker_len + 1):
            if input_ids[i:i + marker_len].tolist() == assistant_marker:
                marker_pos = i + marker_len  # position right after marker
                break

        if marker_pos >= 0:
            labels[:marker_pos] = -100
        else:
            # Fallback: mask first 80% (shouldn't happen with correct template)
            labels[:int(len(labels) * 0.8)] = -100

        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "labels": labels,
        }


class CorrectionCollator:
    """Pads batch to same length, left-padding for causal LM."""

    def __init__(self, tokenizer):
        self.tokenizer = tokenizer
        self.pad_id = tokenizer.pad_token_id or tokenizer.eos_token_id

    def __call__(self, features):
        max_len = max(f["input_ids"].size(0) for f in features)

        input_ids = []
        attention_mask = []
        labels = []

        for f in features:
            pad_len = max_len - f["input_ids"].size(0)
            input_ids.append(torch.cat([
                torch.full((pad_len,), self.pad_id, dtype=torch.long),
                f["input_ids"],
            ]))
            attention_mask.append(torch.cat([
                torch.zeros(pad_len, dtype=torch.long),
                f["attention_mask"],
            ]))
            labels.append(torch.cat([
                torch.full((pad_len,), -100, dtype=torch.long),
                f["labels"],
            ]))

        return {
            "input_ids": torch.stack(input_ids),
            "attention_mask": torch.stack(attention_mask),
            "labels": torch.stack(labels),
        }


def main():
    parser = argparse.ArgumentParser(description="Train BCI spelling correction (text-only)")
    parser.add_argument("--data_dir", type=str, default="data/correction")
    parser.add_argument("--output_dir", type=str, default="output/correction")
    parser.add_argument("--model_name", type=str, default="Qwen/Qwen3-4B-Instruct-2507")
    parser.add_argument("--from_modelscope", action="store_true", default=True)
    # LoRA
    parser.add_argument("--lora_rank", type=int, default=16)
    parser.add_argument("--lora_alpha", type=int, default=32)
    parser.add_argument("--lora_dropout", type=float, default=0.05)
    # Training
    parser.add_argument("--batch_size", type=int, default=8)
    parser.add_argument("--grad_accum", type=int, default=2)
    parser.add_argument("--lr", type=float, default=2e-4)
    parser.add_argument("--epochs", type=int, default=10)
    parser.add_argument("--early_stopping", type=int, default=3)
    parser.add_argument("--warmup_ratio", type=float, default=0.1)
    parser.add_argument("--max_length", type=int, default=1280)
    args = parser.parse_args()

    # Load model
    if args.from_modelscope:
        from modelscope import snapshot_download
        model_path = snapshot_download(args.model_name)
    else:
        model_path = args.model_name

    print(f"Loading {args.model_name}...")
    tokenizer = AutoTokenizer.from_pretrained(
        model_path, trust_remote_code=True, padding_side="left",
    )
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        torch_dtype=torch.bfloat16,
        trust_remote_code=True,
        low_cpu_mem_usage=True,
    )

    # Apply LoRA
    lora_config = LoraConfig(
        r=args.lora_rank,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
        task_type="CAUSAL_LM",
        bias="none",
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    # Load datasets
    data_dir = Path(args.data_dir)
    train_dataset = CorrectionDataset(data_dir / "train.jsonl", tokenizer, args.max_length)
    val_dataset = CorrectionDataset(data_dir / "val.jsonl", tokenizer, args.max_length)
    collator = CorrectionCollator(tokenizer)

    # Training args
    training_args = TrainingArguments(
        output_dir=args.output_dir,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size * 2,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.lr,
        warmup_ratio=args.warmup_ratio,
        lr_scheduler_type="cosine",
        bf16=True,
        logging_steps=10,
        eval_strategy="epoch",
        save_strategy="epoch",
        save_total_limit=3,
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
        report_to="tensorboard",
        logging_dir=f"{args.output_dir}/logs",
        dataloader_num_workers=2,
        dataloader_pin_memory=True,
        remove_unused_columns=False,
        gradient_checkpointing=True,
        gradient_checkpointing_kwargs={"use_reentrant": False},
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        data_collator=collator,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=args.early_stopping)],
    )

    print("Starting training...")
    trainer.train()

    # Save final
    final_dir = Path(args.output_dir) / "final"
    model.save_pretrained(str(final_dir))
    tokenizer.save_pretrained(str(final_dir))
    print(f"Model saved to {final_dir}")


if __name__ == "__main__":
    main()
